services:
  postgres:
    image: postgres:16.0
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'" ]
      interval: 1s
      timeout: 1s
      retries: 5

  app-jvm:
    image: datadog-crash-jvm
    ports:
      - "8080:8080"
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
        SPRING_DATASOURCE_PASSWORD: password
        SPRING_DATASOURCE_USERNAME: user

  app-native:
    image: datadog-crash-native
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_USERNAME: user

  flyway-clean:
    image: flyway/flyway:latest
    container_name: flyway-clean
    command: -url=jdbc:postgresql://postgres:5432/postgres -user=user -password=password -connectRetries=60 clean
    environment:
      FLYWAY_CLEAN_DISABLED: false
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src/db:/flyway/sql
  flyway-migrate:
    image: flyway/flyway:latest
    container_name: flyway-migrate
    command: -url=jdbc:postgresql://postgres:5432/postgres -user=user -password=password -connectRetries=60 migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src/db:/flyway/sql